server:
  port: 80
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 9024
spring:
  datasource:
    url: jdbc:mysql://www.201408.top:3306/vsum
    username: Dim
    password: dim.gold
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: gold.dim.springbootdemo.entity